### ISSUE TITLE
Is it possible to get the gen-cert.sh working on mac?

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/Word-Add-in-JS-Redact#2]
This script doesn't work on mac:

https://github.com/OfficeDev/Word-Add-in-JS-Redact/blob/master/gen-cert.sh

**Comment by Rick-Kirkham** [comment]
That Git bash script only works on Windows. Although an Office Add-in should _run_ in Office for Mac, we generally assume that you will be _developing_ your add-in on a Windows computer. If you want to try developing on a Mac, you will need to install/enable a server on the Mac, and create a self-signed certificate for that server. The Mac has a built-in Apache server (which is not enabled by default). There are also other server applications that can be installed on a Mac.

I would recommend that you go to www.bing.com and try the following searches:

- How to enable Apache on Mac
- How to create a self-signed certificate on a Mac
- How to enable HTTPS on a Mac
- How to trust a certificate on a mac

In general, since an Office Add-in is a web application at heart, what you need to know is how to develop/host a web application that supports HTTPS on a Mac.

**Comment by fergiemcdowall** [comment]
> we generally assume that you will be developing your add-in on a Windows computer

Well kudos to you guys for that no longer being a hard requirement :) but I totally understand that platform independence requires a lot of work.
